bot:
  name: ${BOT_NAME:economka}
  token: ${BOT_TOKEN:8320437220:AAHagPcX66h7-k33IAb5zfw1GjXbK3cXrPE}

spring:
  application:
  name: economca
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}