bot:
  name: ${BOT_NAME:economka}
  token: ${BOT_TOKEN:8320437220:AAHagPcX66h7-k33IAb5zfw1GjXbK3cXrPE}

spring:
  docker:
    compose:
      file: ./compose.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    default-schema: public
    drop-first: false

  datasource:
    url: jdbc:postgresql://${PG_URL:localhost:5432}/postgres
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
