bot:
  name: ${BOT_NAME:economca}
  token: ${BOT_TOKEN:8231667222:AAE7pgst5e3U309oIV-ytZFfDoJIBX8Vy5s}

spring:
  docker:
    compose:
      file: ./compose.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${PG_URL:localhost:5432}/postgres
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
